createdAt: "2023-08-27 15:26:31"
description: This is an example application for demo purpose
environ:
  include: ./system/apprun-environ.yaml
longName: Example Application
name: 1-apiclient
productGroup: demo product
resources:
- include: system/default-api-flow.yaml
- include: flow
triggers:
- handlers:
  - actions:
    - ref: '#flow'
      settings:
        flowURI: res://flow.timer.5183a406-1810-489c-a90a-71965e306abb-timer_0
    settings:
      repeatInterval: 10m
      startDelay: 30s
  id: timer.5183a406-1810-489c-a90a-71965e306abb-timer_0
  ref: timer
type: app
updatedAt: "2023-08-27 15:28:17"
version: 1.0.0
